# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- checkout: self
  persistCredentials: true

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'f787e026-7c19-4b78-92df-67dd5db79642'
    definition: '208'
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    artifactName: 'sdk'
    itemPattern: |
      sdk/*.dmg
      !xcframework/**
    targetPath: '$(Agent.TempDirectory)/sdk'

- script: |
    git config user.email "krishna.lolage@microsoft.com"
    git config user.name "klolage"
    git pull
    git checkout release/v5.7.1
  displayName: 'Checkout release branch'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Agent.TempDirectory)/sdk/sdk\xcframework/xcframework/*.dmg'
    destinationFolder: '$(Agent.TempDirectory)/extracted_sdk'
    cleanDestinationFolder: true
    overwriteExistingFiles: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Agent.TempDirectory)/extracted_sdk/DragonMedicalSpeechKit/DragonMedicalSpeechKit/DragonMedicalSpeechKit.xcframework/DragonMedicalSpeechKit.xcframework'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Agent.TempDirectory)/zipped_sdk/DragonMedicalSpeechKit.zip'
    replaceExistingArchive: true
    verbose: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Agent.TempDirectory)/zipped_sdk/DragonMedicalSpeechKit.zip'
    ArtifactName: 'zip_sdk'
    publishLocation: 'Container'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)/zipped_sdk/'
    Contents: '**'
    TargetFolder: '$(System.DefaultWorkingDirectory)/Sources/SDK'
    CleanTargetFolder: false
    OverWrite: true

- task: CmdLine@2
  inputs:
    script: |
      cd $(Agent.TempDirectory)/extracted_sdk/DragonMedicalSpeechKit/DragonMedicalSpeechKit/DragonMedicalSpeechKit.xcframework/DragonMedicalSpeechKit.bundle
      del "DragonMedicalSpeechKit" "Info.plist"
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)/extracted_sdk/DragonMedicalSpeechKit/DragonMedicalSpeechKit/DragonMedicalSpeechKit.xcframework/DragonMedicalSpeechKit.bundle'
    Contents: '**'
    TargetFolder: '$(System.DefaultWorkingDirectory)/Sources/SDK/Bundle/'
    CleanTargetFolder: false
    OverWrite: true

- script: |
    git status
    git pull
    git add Sources/SDK/DragonMedicalSpeechKit.zip
    git add Sources/SDK/Bundle/
    git commit -m "Uploaded SDK"
    git push
  displayName: 'Git Status'